Truncate table [EDI].[Languages];

INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('0','Unknown','Inconnu',15,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('10','Afrikaans','Afrikaans',20,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('20','Albanian','Albanais',25,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('25','Amharic','Amharique',30,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('30','Arabic','Arabe',35,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('40','Armenian','Arménien',40,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('42','Ashanti','Asante',45,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('45','Assyrian','Assyrien',50,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('50','Azeri','Azéri',55,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('60','Bengali','Bengalais',60,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('70','Bihari','Bihari',65,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('80','Bulgarian','Bulgare',70,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('90','Burmese','Birman',75,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('100','Cantonese','Cantonais',80,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('105','Chiu Chow','Chiu Chow',85,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('108','Cree','Crie',90,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('110','Czech','Tchčque',95,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('120','Danish','Danois',100,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('125','Dari','Dari',105,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('130','Dutch/Flemish','Hollandais/flamand',110,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('135','Egyptian','Égyptien',115,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('140','English','Anglais',120,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('150','Estonian','Estonien',125,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('155','Ethiopian','Éthiopien',130,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('160','Finnish','Finlandais',145,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('170','French','Français',150,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('175','Fukienese','Fou-kien',155,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('180','Gaelic','Gaélique',160,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('190','German','Allemand',165,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('200','Greek','Grec',175,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('210','Gujarati','Gujarati',180,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('215','Hakka','Hakka',185,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('220','Hebrew','Hébreu',190,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('230','Hindi','Hindi',195,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('240','Hindustani','Hindustani',200,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('245','Hok Chiu','Hok Chiu',205,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('250','Hungarian','Hongrois',210,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('260','Icelandic','Islandais',215,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('270','Ilocano','Ilocano',220,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('275','Indigenous (North American)','Autochtones (Amérique du Nord)',225,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('280','Indigenous (South American)','Autochtones (Amérique du Sud)',230,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('285','Inuktitut','Inuktitut',240,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('290','Italian','Italien',245,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('295','Jaffna','Jaffna',250,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('300','Japanese','Japonais',255,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('310','Katchi','Katchi',270,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('320','Kannada','Canara',260,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('330','Kashmiri','Kashméré',265,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('335','Khmer','Kampuchéen',275,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('340','Korean','Coréen',290,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('345','Lao','Lao',300,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('350','Latvian','Lettonien',305,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('355','Lebanese','Libanais',310,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('360','Lithuanian','Lithuanien',320,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('370','Macedonian','Macédonien',325,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('375','Malayalam','Malayalam',330,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('380','Indonesian/Malay','Indonésien/malais',235,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('400','Mandarin','Mandarin',335,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('410','Marathi','Marathi',345,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('415','Mohawk','Mohawk',355,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('420','Norwegian','Norvégien',360,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('422','Ojibway','Ojibway',365,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('425','Pashto/Pushtu','Afhgan/Pachtou',370,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('430','Farsi/Persian','Parsi/Persan',135,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('440','Polish','Polonais',380,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('450','Portuguese','Portugais',385,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('460','Punjabi','Punjabi',390,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('480','Romanian','Roumain',395,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('490','Russian','Russe',400,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('495','Serbian','Serbe',405,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('500','Serbo-Croatian','Serbo-croate',410,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('505','Sindhi','Sindhi',415,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('510','Singhalese','Cinghalais',420,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('520','Slovak','Slovaque',425,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('530','Slovenian','Slovčne',430,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('535','Somali','Somalien',435,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('540','Spanish','Espagnol',440,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('550','Swahili','Swahili',445,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('560','Swedish','Suédois',450,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('570','Filipino/Tagalog','Philippin/tagalog',140,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('580','Tamil','Tamoul',455,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('600','Thai','Thai',460,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('610','Tigrinia','Tigrigna',465,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('620','Turkish','Turque',470,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('630','Twi','Twi',475,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('640','Ukrainian','Ukrainien',480,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('650','Urdu','Urdu',485,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('660','Vietnamese','Vietnamien',490,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('670','Welsh','Gallois',495,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('680','Patois/Creole','Patois/créole',375,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('685','Xhosa','Xhosa',505,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('690','Yiddish','Yiddish',510,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('700','Yoruba','Yoruba',515,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('710','Other','Autre',520,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('720','Other Chinese','Autre langue chinoise',525,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('730','Other African','Autre langue africaine',530,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('740','Other Indian (Asia)','Autre langue indienne (Asie)',535,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('750','Other Asian','Autre langue asiatique',540,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('760','Other European','Autre langue européenne',545,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('365','Lingala','Lingala',315,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('195','Grebo','Grebo',170,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('342','Kurdish','Kurde',295,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('315','Kirundi','Kirundi',285,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('325','Kinyarwanda','Kinyarwanda',280,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('378','Manding','Mandingues',340,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('675','Wolastoqiyik (Maliseet) ','Wolastoqiyik (Maliseet) ',500,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('412','mi''kmaq','mi''kmaq',350,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('170','French','Français',10,getDate(),'System',getDate(),'System')
INSERT INTO [EDI].[Languages]([Code],[English],[French],[Sequence],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])VALUES('140','English','Anglais',5,getDate(),'System',getDate(),'System')
