// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EDI.ApplicationCore.Entities
{
    [Table("Children", Schema = "EDI")]
    public partial class Child : BaseEntity
    {
        public Child()
        {
            QuestionnairesDataDemographics = new HashSet<QuestionnairesDataDemographic>();
            QuestionnairesDataSectionAs = new HashSet<QuestionnairesDataSectionA>();
            QuestionnairesDataSectionBs = new HashSet<QuestionnairesDataSectionB>();
            QuestionnairesDataSectionCs = new HashSet<QuestionnairesDataSectionC>();
            QuestionnairesDataSectionDs = new HashSet<QuestionnairesDataSectionD>();
            QuestionnairesDataSectionEs = new HashSet<QuestionnairesDataSectionE>();
        }

        public string Ediid { get; set; }
        public string LocalId { get; set; }
        /// <summary>
        /// Year of the EDI implementation
        /// </summary>
        public int? YearId { get; set; }
        public int? TeacherId { get; set; }
        public int? GenderId { get; set; }
        public int? ChildStatusId { get; set; }
        public DateTime? Dob { get; set; }
        public string PostalCode { get; set; }
        public string ChildNumber { get; set; }

        public virtual Gender Gender { get; set; }
        [JsonIgnore]
        public virtual Teacher Teacher { get; set; }
        public virtual Year Year { get; set; }
        public virtual ChildStatus ChildStatus { get; set; }
        public virtual ICollection<QuestionnairesDataDemographic> QuestionnairesDataDemographics { get; set; }
        public virtual ICollection<QuestionnairesDataSectionA> QuestionnairesDataSectionAs { get; set; }
        public virtual ICollection<QuestionnairesDataSectionB> QuestionnairesDataSectionBs { get; set; }
        public virtual ICollection<QuestionnairesDataSectionC> QuestionnairesDataSectionCs { get; set; }
        public virtual ICollection<QuestionnairesDataSectionD> QuestionnairesDataSectionDs { get; set; }
        public virtual ICollection<QuestionnairesDataSectionE> QuestionnairesDataSectionEs { get; set; }        
    }
}