// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace EDI.ApplicationCore.Entities
{
    public partial class Faq
    {
        public int Id { get; set; }
        public int YearId { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public bool? IsTeacherFaq { get; set; }
        public bool? IsAdministratorFaq { get; set; }
        public bool? IsCoordinatorFaq { get; set; }
        public short Sequence { get; set; }
        public DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }

        public virtual Year Year { get; set; }
    }
}