// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EDI.ApplicationCore.Entities
{
    [Table("FileImportStatus", Schema = "LUData")]
    public partial class FileImportStatus:BaseEntity
    {
        public FileImportStatus()
        {
            FileImports = new HashSet<FileImport>();
        }

        public string Code { get; set; }
        public string English { get; set; }
        public string French { get; set; }
        public int? Sequence { get; set; }

        public virtual ICollection<FileImport> FileImports { get; set; }
    }
}