// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace EDI.ApplicationCore.Entities
{
    [Table("FileImports", Schema = "Staging")]
    public partial class FileImport:BaseEntity
    {        
        public string FileName { get; set; }
        public string SiteName { get; set; }
        public string CoordinatorName { get; set; }
        public string CoordinatorEmail { get; set; }
        public string SchoolName { get; set; }
        //public int? SchoolProvinceId { get; set; }
        public string TeacherName { get; set; }
        public string TeacherEmail { get; set; }
        public string LocalId { get; set; }
        //public byte? ClassTime { get; set; }
        public int? GenderId { get; set; }
        public DateTime? ChildDob { get; set; }
        public string ChildPostalCodeZip { get; set; }
        public string ChildEdiid { get; set; }
        public int? FileImportStatusId { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Province SchoolProvince { get; set; }
        public virtual FileImportStatus FileImportStatus { get; set; }

    }
}