// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace EDI.ApplicationCore.Entities
{
    public partial class Link
    {
        public int Id { get; set; }
        public int YearId { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public string Description { get; set; }
        public bool? IsTeacherLink { get; set; }
        public bool? IsAdminLink { get; set; }
        public bool? IsCoordinatorLink { get; set; }
        public short Sequence { get; set; }
        public DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }

        public virtual Year Year { get; set; }
    }
}