// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EDI.ApplicationCore.Entities
{
    [Table("Links", Schema = "EDI")]
    public partial class Link:BaseEntityProvinceConfiguration
    {        
        public int YearId { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public string Description { get; set; }
        public bool? IsTeacherLink { get; set; }
        public bool? IsAdminLink { get; set; }
        public bool? IsCoordinatorLink { get; set; }
        public short Sequence { get; set; }

        public virtual Year Year { get; set; }
    }
}