// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace EDI.ApplicationCore.Entities
{
    public partial class LookupSet:BaseEntity
    {       
        public int YearId { get; set; }
        public byte? LookupId { get; set; }
        public string LookupName { get; set; }
        public string English { get; set; }
        public string French { get; set; }
        public byte Value { get; set; }
        public short Sequence { get; set; }
        
        public virtual Year Year { get; set; }
    }
}