// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EDI.ApplicationCore.Entities
{ 
[Table("NewsFeed", Schema = "EDI")]
public partial class NewsFeed:BaseEntityProvinceConfiguration
    {        
        public string Title { get; set; }
        public string Summary { get; set; }
        public string Text { get; set; }
        public string Author { get; set; }
        /// <summary>
        /// Year of the EDI implementation
        /// </summary>
        public int YearId { get; set; }
        public DateTime? ValidFrom { get; set; }
        public DateTime? ValidTo { get; set; }
        public virtual Year Year { get; set; }
    }
}