// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace EDI.ApplicationCore.Entities
{
    public partial class Orientation
    {
        public Orientation()
        {
            QuestionnairesConfigurations = new HashSet<QuestionnairesConfiguration>();
        }

        public int Id { get; set; }
        public int? YearId { get; set; }
        public string English { get; set; }
        public string French { get; set; }
        public DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }

        public virtual Year Year { get; set; }
        public virtual ICollection<QuestionnairesConfiguration> QuestionnairesConfigurations { get; set; }
    }
}