// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace EDI.ApplicationCore.Entities
{
    [Table("Questionnaires.Data.SectionC", Schema = "EDI")]
    public partial class QuestionnairesDataSectionC:BaseEntityQuestionnaire
    {
        public int ChildId { get; set; }
        public byte? Social { get; set; }
        public byte? Peers { get; set; }
        public byte? Cooperative { get; set; }
        public byte? Play { get; set; }
        public byte? Rules { get; set; }
        public byte? RespectsProperty { get; set; }
        public byte? SelfControl { get; set; }
        public byte? SelfConfidence { get; set; }
        public byte? RespectsAdults { get; set; }
        public byte? RespectsChildren { get; set; }
        public byte? Responsible { get; set; }
        public byte? Listens { get; set; }
        public byte? Directions { get; set; }
        public byte? WorkOnTime { get; set; }
        public byte? Independent { get; set; }
        public byte? TakesCard { get; set; }
        public byte? Neat { get; set; }
        public byte? Curious { get; set; }
        public byte? EagerNewToy { get; set; }
        public byte? EagerNewGame { get; set; }
        public byte? EagerRead { get; set; }
        public byte? SolvesProblem { get; set; }
        public byte? FollowInstruction1Step { get; set; }
        public byte? Routines { get; set; }
        public byte? RoutineChanges { get; set; }
        public byte? AnswersQuestions { get; set; }
        public byte? Tolerance { get; set; }
        public byte? HelpHurt { get; set; }
        public byte? MessCleanup { get; set; }
        public byte? Mediate { get; set; }
        public byte? AssistOthers { get; set; }
        public byte? Comforting { get; set; }
        public byte? HelpPickUpObjects { get; set; }
        public byte? IncludesOthers { get; set; }
        public byte? HelpSick { get; set; }
        public byte? Separation { get; set; }
        public byte? Fights { get; set; }
        public byte? Bullies { get; set; }
        public byte? KicksHits { get; set; }
        public byte? Takes { get; set; }
        public byte? LaughsAtOthers { get; set; }
        public byte? Restless { get; set; }
        public byte? Distactable { get; set; }
        public byte? Fidgets { get; set; }
        public byte? Disobedient { get; set; }
        public byte? Temper { get; set; }
        public byte? Impulsive { get; set; }
        public byte? TakingTurns { get; set; }
        public byte? Settle { get; set; }
        public byte? Inattentive { get; set; }
        public byte? Unhappy { get; set; }
        public byte? Fearful { get; set; }
        public byte? Worried { get; set; }
        public byte? Cries { get; set; }
        public byte? Nervous { get; set; }
        public byte? NoDecisions { get; set; }
        public byte? Shy { get; set; }
        public byte? SucksThumb { get; set; }
        [JsonIgnore]
        public virtual Child Child { get; set; }
    }
}