// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EDI.ApplicationCore.Entities
{
    [Table("Questionnaires.Data.Demographics", Schema = "EDI")]
    public partial class QuestionnairesDataDemographic:BaseEntityQuestionnaire
    {
        public int ChildId { get; set; }        
        public byte? StudentStatus { get; set; }
        public byte? ClassAssignment { get; set; }
        public DateTime? Dob { get; set; }
        public byte? AttendedJk { get; set; }
        public byte? Jkteacher { get; set; }
        public int? GenderId { get; set; }
        public string PostalCode { get; set; }
        public byte? ClassType { get; set; }
        public byte? SpecialNeeds { get; set; }
        public byte? ConsideredEsl { get; set; }             
        public bool? IPRC { get; set; }
        public bool? IEP { get; set; }
        public bool? SpecialEducation { get; set; }
        public bool? Gifted { get; set; }
        public byte? EFSL { get; set; }
        public byte? FrenchImmersion { get; set; }
        public byte? OtherImmersion { get; set; }
        public byte? EthnicStatus { get; set; }
        public byte? Communicates { get; set; }
        public bool? Chipewyan { get; set; }
        public bool? Cree { get; set; }
        public bool? English { get; set; }
        public bool? French { get; set; }
        public bool? Gwichin { get; set; }
        public bool? Inuinnaqtun { get; set; }
        public bool? Inuktitut { get; set; }
        public bool? Inuvialuktun { get; set; }
        public bool? NorthSlavey { get; set; }
        public bool? SouthSlavey { get; set; }
        public bool? Tlicho { get; set; }
        public int? OtherLanguage { get; set; }
        public byte? IndigenousAncestry { get; set; }
        public byte? AfricanDescent { get; set; }
        public int? FirstLanguage1 { get; set; }
        public int? FirstLanguage2 { get; set; }
        public int? FirstLanguage3 { get; set; }
        public int? Ethnicity { get; set; }
        public byte? SpecialNeedsReferral { get; set; }
        public byte? ClassTime { get; set; }
        public byte? ELL { get; set; }
        public string ClassTimeSpecify { get; set; }
        public byte? LandAgreement { get; set; }
        /* 2022 Demographics*/        
        public byte? InstructionFormat { get; set; }
        public string InstructionFormatSpecify { get; set; }
        public byte? OnlineChallenges { get; set; }
        public string OnlineChallengesSpecify { get; set; }
        public bool? OnlineChallengesNA { get; set; }
        public bool? OnlineChallengesNoInternet { get; set; }
        public bool? OnlineChallengesLimitedTech { get; set; }
        public bool? OnlineChallengesNoAdultSupport { get; set; }
        public bool? OnlineChallengesUninterested { get; set; }
        public bool? OnlineChallengesNoLearningSpace { get; set; }
        public bool? OnlineChallengesNoSupplies { get; set; }
        public bool? OnlineChallengesOther { get; set; }

        /* End 2022 Demographics*/

        [JsonIgnore]
        public virtual Child Child { get; set; }
        [JsonIgnore]
        public virtual Questionnaire Questionnaire { get; set; }
        public virtual Gender Gender { get; set; }
    }
}