// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace EDI.ApplicationCore.Entities
{
    [Table("Questionnaires.Data.SectionB", Schema = "EDI")]
    public partial class QuestionnairesDataSectionB:BaseEntityQuestionnaire
    {
        public int ChildId { get; set; }
        public byte? Effective { get; set; }
        public byte? Listens { get; set; }
        public byte? Tells { get; set; }
        public byte? Imagines { get; set; }
        public byte? Communicates { get; set; }
        public byte? Understands { get; set; }
        public byte? Articulates { get; set; }
        public byte? Handles { get; set; }
        public byte? Books { get; set; }
        public byte? Reading { get; set; }
        public byte? Letters10 { get; set; }
        public byte? Sounds { get; set; }
        public byte? Rhyming { get; set; }
        public byte? GroupReading { get; set; }
        public byte? SimpleWords { get; set; }
        public byte? ComplexWords { get; set; }
        public byte? SimpleSentences { get; set; }
        public byte? Writing { get; set; }
        public byte? WritingDirections { get; set; }
        public byte? Voluntarily { get; set; }
        public byte? WritesName { get; set; }
        public byte? WriteSimpleWords { get; set; }
        public byte? WriteSimpleSentences { get; set; }
        public byte? Remembers { get; set; }
        public byte? Mathematics { get; set; }
        public byte? NumberGames { get; set; }
        public byte? Sorting { get; set; }
        public byte? OneToOne { get; set; }
        public byte? Count20 { get; set; }
        public byte? Recognize10 { get; set; }
        public byte? Bigger { get; set; }
        public byte? Shapes { get; set; }
        public byte? TimeConcepts { get; set; }
        public byte? SpecialNumSkills { get; set; }
        public byte? SpecialLitSkills { get; set; }
        public byte? SpecialArtSkills { get; set; }
        public byte? SpecialMusSkills { get; set; }
        public byte? SpecialAthSkills { get; set; }
        public byte? SpecialPblskills { get; set; }
        public byte? SpecialOthSkills { get; set; }
        public string OtherSkills { get; set; }
        [JsonIgnore]
        public virtual Child Child { get; set; }
        [JsonIgnore]
        public virtual Questionnaire Questionnaire { get; set; }
    }
}