// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace EDI.ApplicationCore.Entities
{
    [Table("Questionnaires.Data.SectionE", Schema = "EDI")]
    public partial class QuestionnairesDataSectionE:BaseEntityQuestionnaire
    {
        public int ChildId { get; set; }
        public byte? Birth1 { get; set; }
        public byte? One2 { get; set; }
        public byte? Two3 { get; set; }
        public byte? Three4 { get; set; }
        public byte? Four5 { get; set; }
        public byte? FamilyLiteracy { get; set; }
        public byte? FamilyResource { get; set; }
        public byte? LibraryReading { get; set; }
        public byte? MusicArts { get; set; }
        public byte? Sports { get; set; }
        public byte? Clubs { get; set; }
        public byte? Cultural { get; set; }
        public byte? Langauges { get; set; }
        public byte? Religion { get; set; }
        public byte? Other { get; set; }
        public string OtherSpecify { get; set; }
        public byte? NSECDIS { get; set; }
        public byte? EIBI { get; set; }
        public byte? NSHS { get; set; }
        public byte? OtherServices { get; set; }
        public string OtherServicesSpecify { get; set; }
        public byte? PrePrimary { get; set; }
        public byte? CentreBased { get; set; }
        public string DaycareName { get; set; }
        public byte? HomeDaycare { get; set; }
        public string HomeDaycareName { get; set; }
        public byte? NonParentInHome { get; set; }
        public byte? InterventionProgram { get; set; }
        public string InterventionProgramSpecify { get; set; }
        public byte? NonParentalCare { get; set; }
        public bool? CentreBasedSchool { get; set; }
        public bool? CentreBasedCommunity { get; set; }
        public bool? HomeBased { get; set; }
        public bool? ChildHomeNonRelative { get; set; }
        public bool? ChildHomeRelative { get; set; }
        public bool? PreSchool { get; set; }
        public bool? OtherCare { get; set; }
        public byte? PriorArrangement { get; set; }
        public byte? CommunityLearning { get; set; }    
        public string CommunityLearningSpecify { get; set; }
        public byte? Year1JK { get; set; }
        public byte? NonParentCareBefore{ get; set; }
        public byte? NonParentCareAfter { get; set; }
        public byte? CareArrangementBefore { get; set; }
        public byte? CareArrangementAfter { get; set; }
        public byte? DroppedOff { get; set; }
        public byte? PickedUp { get; set; }
        public bool? US_CentreBased { get; set; }
        public bool? US_ChildHome { get; set; }
        public bool? US_OtherHomeBased { get; set; }
        public bool? US_Other { get; set; }
        public string US_OtherSpecify { get; set; }
        public bool? US_DontKnow{ get; set; }
        public byte? Volunteered { get; set; }
        public string VolunteeredSpecify { get; set; }
        public byte? ParentTeacherConference { get; set; }
        public byte? OneOnOneConference { get; set; }
        public byte? HomeworkAssistance { get; set; }
        public byte? OrganizedPreSchool { get; set; }
        public bool? CentreBasedCare { get; set; }
        public string Comments { get; set; }

        /* 2023 SectionE*/
        /* NL */
        public byte? AttendedNature { get; set; }
        /* MB */
        public bool? CentreBasedLicensedNonProfit { get; set; }
        public bool? CentreBasedLicensedProfit { get; set; }
        public bool? OtherHomeLicensed { get; set; }
        public bool? OtherHomeUnlicensedNonRelative { get; set; }
        public bool? OtherHomeUnlicensedRelative { get; set; }
        public bool? CentreBasedLicensed { get; set; }
        public bool? HomeUnlicensedNonRelative { get; set; }
        public bool? Relative { get; set; }

        /*PEI*/
        public byte? IBIPrior { get; set; }
        public byte? IBIDuring { get; set; }
        public byte? IBIBoth { get; set; }
        public byte? OrganizedSocial { get; set; }

        public byte? FirstNations { get; set; }
        public byte? Inuit { get; set; }
        public byte? Metis { get; set; }
        public byte? OtherIndigenous { get; set; }

        /* AB */
        public byte? HeadStart { get; set; }
        public byte? CreeSpeaker { get; set; }

        /* 2023 End SectionE*/

        /* 2025 PEI */
        public byte? ParentalEngagement { get; set; }

        [JsonIgnore]
        public virtual Child Child { get; set; }
        [JsonIgnore]
        public virtual Questionnaire Questionnaire { get; set; }
    }
}