// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EDI.ApplicationCore.Entities
{
    [Table("Schools", Schema = "EDI")]
    public partial class Schools:BaseEntity
    {
        public string SchoolNumber { get; set; }
        public string SchoolName { get; set; }
        public int CountryId { get; set; }
        public int ProvinceId { get; set; }
        public int SiteId { get; set; }
        public string City { get; set; }
        public bool? Elpschool { get; set; }
        public string Description { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }

        public virtual Sites Sites { get; set; }

        public virtual Countries Countries { get; set; }
    }
}