// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EDI.ApplicationCore.Entities
{
    [Table("Schools", Schema = "EDI")]
    public partial class School:BaseEntity
    {
        public School()
        {
            Teachers = new HashSet<Teacher>();
        }

        public string SchoolNumber { get; set; }
        /// <summary>
        /// Year of the EDI implementation
        /// </summary>
        public int? YearId { get; set; }
        public string SchoolName { get; set; }
        public int CountryId { get; set; }
        public int ProvinceId { get; set; }
        public int SiteId { get; set; }
        public string City { get; set; }
        public string Description { get; set; }

        public virtual Country Country { get; set; }
        public virtual Province Province { get; set; }
        public virtual Site Site { get; set; }
        public virtual Year Year { get; set; }
        [JsonIgnore]
        public virtual ICollection<Teacher> Teachers { get; set; }
    }
}