// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace EDI.ApplicationCore.Entities
{
    public partial class Site
    {
        public int SiteId { get; set; }
        public string SiteName { get; set; }
        public string Description { get; set; }
        /// <summary>
        /// guid from EDI.Identity.dbo.ASPNETUsers
        /// </summary>
        public string CoordinatorId { get; set; }
        public DateTime CreatedDate { get; set; }
    }
}