// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EDI.ApplicationCore.Entities
{
    [Table("Translations", Schema = "LUData")]
    public partial class Translation:BaseEntity
    {
        public string English { get; set; }
        public string French { get; set; }
    }
}