// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EDI.ApplicationCore.Entities
{
    [Table("Years", Schema = "LUData")]
    public partial class Year:BaseEntity
    {
        public Year()
        {
            // add lookupdata to the years
            Children = new HashSet<Child>();
            Coordinators = new HashSet<Coordinator>();
            Faqs = new HashSet<Faq>();
            Links = new HashSet<Link>();
            LookupSets = new HashSet<LookupSet>();
            LookupSetOptions = new HashSet<LookupSetOption>();
            NewsFeeds = new HashSet<NewsFeed>();
            Schools = new HashSet<School>();
            Sites = new HashSet<Site>();
            TeacherFeedbackForms = new HashSet<TeacherFeedbackForm>();
            TeacherParticipationForms = new HashSet<TeacherParticipationForm>();
            Teachers = new HashSet<Teacher>();
        }
        public short? Ediyear { get; set; }

        public virtual ICollection<Child> Children { get; set; }
        public virtual ICollection<Coordinator> Coordinators { get; set; }
        public virtual ICollection<Faq> Faqs { get; set; }
        public virtual ICollection<Link> Links { get; set; }
        public virtual ICollection<LookupSet> LookupSets { get; set; }
        public virtual ICollection<LookupSetOption> LookupSetOptions { get; set; }
        public virtual ICollection<NewsFeed> NewsFeeds { get; set; }
        public virtual ICollection<School> Schools { get; set; }
        public virtual ICollection<Site> Sites { get; set; }
        public virtual ICollection<TeacherFeedbackForm> TeacherFeedbackForms { get; set; }
        public virtual ICollection<TeacherParticipationForm> TeacherParticipationForms { get; set; }
        public virtual ICollection<Teacher> Teachers { get; set; }
    }
}