// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EDI.ApplicationCore.Entities
{
    [Table("Years", Schema = "LUData")]
    public partial class Year : BaseEntityProvinceConfiguration
    {
        public Year()
        {
            Children = new HashSet<Child>();
            Coordinators = new HashSet<Coordinator>();
            Faqs = new HashSet<Faq>();
            InputTypes = new HashSet<InputType>();
            Links = new HashSet<Link>();
            LookupSets = new HashSet<LookupSet>();
            NewsFeeds = new HashSet<NewsFeed>();
            Orientations = new HashSet<Orientation>();
            Questionnaires = new HashSet<Questionnaire>();
            QuestionnairesConfigurations = new HashSet<QuestionnairesConfiguration>();
            QuestionnairesDataDemographics = new HashSet<QuestionnairesDataDemographic>();
            QuestionnairesDataSectionAs = new HashSet<QuestionnairesDataSectionA>();
            QuestionnairesDataSectionBs = new HashSet<QuestionnairesDataSectionB>();
            QuestionnairesDataSectionCs = new HashSet<QuestionnairesDataSectionC>();
            QuestionnairesDataSectionDs = new HashSet<QuestionnairesDataSectionD>();
            QuestionnairesDataSectionEs = new HashSet<QuestionnairesDataSectionE>();
            QuestionnairesDataTeacherProfiles = new HashSet<QuestionnairesDataTeacherProfile>();
            Schools = new HashSet<School>();
            Sites = new HashSet<Site>();
            Teachers = new HashSet<Teacher>();
        }
        public short? Ediyear { get; set; }

        public virtual ICollection<Child> Children { get; set; }
        public virtual ICollection<Coordinator> Coordinators { get; set; }
        public virtual ICollection<Faq> Faqs { get; set; }
        public virtual ICollection<InputType> InputTypes { get; set; }
        public virtual ICollection<Link> Links { get; set; }
        public virtual ICollection<LookupSet> LookupSets { get; set; }
        public virtual ICollection<NewsFeed> NewsFeeds { get; set; }
        public virtual ICollection<Orientation> Orientations { get; set; }
        public virtual ICollection<Questionnaire> Questionnaires { get; set; }
        public virtual ICollection<QuestionnairesConfiguration> QuestionnairesConfigurations { get; set; }
        public virtual ICollection<QuestionnairesDataDemographic> QuestionnairesDataDemographics { get; set; }
        public virtual ICollection<QuestionnairesDataSectionA> QuestionnairesDataSectionAs { get; set; }
        public virtual ICollection<QuestionnairesDataSectionB> QuestionnairesDataSectionBs { get; set; }
        public virtual ICollection<QuestionnairesDataSectionC> QuestionnairesDataSectionCs { get; set; }
        public virtual ICollection<QuestionnairesDataSectionD> QuestionnairesDataSectionDs { get; set; }
        public virtual ICollection<QuestionnairesDataSectionE> QuestionnairesDataSectionEs { get; set; }
        public virtual ICollection<QuestionnairesDataTeacherProfile> QuestionnairesDataTeacherProfiles { get; set; }
        public virtual ICollection<School> Schools { get; set; }
        public virtual ICollection<Site> Sites { get; set; }
        public virtual ICollection<Teacher> Teachers { get; set; }
    }
}