// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using EDI.Infrastructure;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using EDI.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using EDI.ApplicationCore.Entities;

namespace EDI.Infrastructure.Data
{
    public class CountryConfiguration : IEntityTypeConfiguration<Country>
    {
        public void Configure(EntityTypeBuilder<Country> entity)
        {
            entity.ToTable("Country");

            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(256);

            entity.Property(e => e.Iso2countryCode)
                .IsRequired()
                .HasColumnName("ISO2CountryCode")
                .HasMaxLength(2);

            entity.Property(e => e.Iso3countryCode)
                .IsRequired()
                .HasColumnName("ISO3CountryCode")
                .HasMaxLength(3);

            entity.Property(e => e.Iso3digitCountry).HasColumnName("ISO3DigitCountry");

            entity.Property(e => e.ModifiedBy)
                .IsRequired()
                .HasMaxLength(256);

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
        }
    }
}
