// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using EDI.Infrastructure;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using EDI.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using EDI.ApplicationCore.Entities;

namespace EDI.Infrastructure.Data
{
    public class DateDimensionConfiguration : IEntityTypeConfiguration<DateDimension>
    {
        public void Configure(EntityTypeBuilder<DateDimension> entity)
        {
            entity.HasKey(e => e.Date);

            entity.ToTable("DateDimension");

            entity.Property(e => e.Date).HasColumnType("date");

            entity.Property(e => e.DaySuffix)
                .IsRequired()
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.DowinMonth).HasColumnName("DOWInMonth");

            entity.Property(e => e.FirstDayOfMonth).HasColumnType("date");

            entity.Property(e => e.FirstDayOfNextMonth).HasColumnType("date");

            entity.Property(e => e.FirstDayOfNextYear).HasColumnType("date");

            entity.Property(e => e.FirstDayOfQuarter).HasColumnType("date");

            entity.Property(e => e.FirstDayOfYear).HasColumnType("date");

            entity.Property(e => e.HolidayText)
                .HasMaxLength(64)
                .IsUnicode(false);

            entity.Property(e => e.IsoweekOfYear).HasColumnName("ISOWeekOfYear");

            entity.Property(e => e.LastDayOfMonth).HasColumnType("date");

            entity.Property(e => e.LastDayOfQuarter).HasColumnType("date");

            entity.Property(e => e.LastDayOfYear).HasColumnType("date");

            entity.Property(e => e.MonthName)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);

            entity.Property(e => e.QuarterName)
                .IsRequired()
                .HasMaxLength(6)
                .IsUnicode(false);

            entity.Property(e => e.WeekDayName)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
        }
    }
}
