// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using EDI.Infrastructure;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using EDI.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using EDI.ApplicationCore.Entities;

namespace EDI.Infrastructure.Data
{
    public class FormConfigurationConfiguration : IEntityTypeConfiguration<FormConfigurations>
    {
        public void Configure(EntityTypeBuilder<FormConfigurations> entity)
        {
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.FieldName).IsUnicode(false);

            entity.Property(e => e.FormName).IsUnicode(false);

            entity.Property(e => e.ModifiedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
        }
    }
}
