// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using EDI.Infrastructure;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using EDI.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using EDI.ApplicationCore.Entities;

namespace EDI.Infrastructure.Data
{
    public class ProvinceTypeConfiguration : IEntityTypeConfiguration<ProvinceType>
    {
        public void Configure(EntityTypeBuilder<ProvinceType> entity)
        {
            entity.ToTable("ProvinceType");

            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(64);

            entity.Property(e => e.ModifiedBy)
                .IsRequired()
                .HasMaxLength(64);

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
        }
    }
}
