// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using EDI.Infrastructure;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using EDI.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using EDI.ApplicationCore.Entities;

namespace EDI.Infrastructure.Data
{
    public class ProvinceConfiguration : IEntityTypeConfiguration<Province>
    {
        public void Configure(EntityTypeBuilder<Province> entity)
        {
            entity.ToTable("Province");

            entity.HasIndex(e => e.CountryId);

            entity.HasIndex(e => e.ProvinceTypeId);

            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.CountryId).HasColumnName("CountryID");

            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(64);

            entity.Property(e => e.ModifiedBy)
                .IsRequired()
                .HasMaxLength(64);

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.Country)
                .WithMany(p => p.Provinces)
                .HasForeignKey(d => d.CountryId);

            entity.HasOne(d => d.ProvinceType)
                .WithMany(p => p.Provinces)
                .HasForeignKey(d => d.ProvinceTypeId);
        }
    }
}
