// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using EDI.Infrastructure;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using EDI.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using EDI.ApplicationCore.Entities;

namespace EDI.Infrastructure.Data
{
    public class SchoolConfiguration : IEntityTypeConfiguration<School>
    {
        public void Configure(EntityTypeBuilder<School> entity)
        {
            entity.ToTable("Schools", "EDI");

            entity.HasIndex(e => e.SchoolNumber)
                .HasName("IX_SchoolNumbers")
                .IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.City).HasMaxLength(100);

            entity.Property(e => e.CountryId).HasColumnName("CountryID");

            entity.Property(e => e.CreatedBy).HasMaxLength(36);

            entity.Property(e => e.Elpschool).HasColumnName("ELPSchool");

            entity.Property(e => e.ModifiedBy).HasMaxLength(36);

            entity.Property(e => e.ProvinceId).HasColumnName("ProvinceID");

            entity.Property(e => e.SchoolName).HasMaxLength(100);

            entity.Property(e => e.SchoolNumber)
                .IsRequired()
                .HasMaxLength(3);

            entity.Property(e => e.SiteId).HasColumnName("SiteID");

            entity.HasOne(d => d.Country)
                .WithMany(p => p.Schools)
                .HasForeignKey(d => d.CountryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Schools_Country");

            entity.HasOne(d => d.Province)
                .WithMany(p => p.Schools)
                .HasForeignKey(d => d.ProvinceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Schools_Province");

            entity.HasOne(d => d.Site)
                .WithMany(p => p.Schools)
                .HasForeignKey(d => d.SiteId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Schools_Sites");
        }
    }
}
