// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using EDI.Infrastructure;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using EDI.ApplicationCore.Entities;

namespace EDI.Infrastructure.Data
{
    public class SiteConfiguration : IEntityTypeConfiguration<Site>
    {
        public void Configure(EntityTypeBuilder<Site> entity)
        {
            entity.ToTable("Sites", "EDI");

            entity.HasIndex(e => e.SiteNumber)
                .HasName("IX_SiteNumbers")
                .IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.CoordinatorId)
                .HasColumnName("CoordinatorID")
                .HasMaxLength(450)
                .HasComment("guid from EDI.Identity.dbo.ASPNETUsers");

            entity.Property(e => e.CreatedBy).HasMaxLength(36);

            entity.Property(e => e.ModifiedBy).HasMaxLength(36);

            entity.Property(e => e.SiteName).HasMaxLength(100);

            entity.Property(e => e.SiteNumber)
                .IsRequired()
                .HasMaxLength(3);
        }
    }
}
