// <auto-generated />
using System;
using EDI.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EDI.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ServiceContext))]
    partial class ServiceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EDI.ApplicationCore.Entities.Child", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ChildNumber")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256)
                        .IsUnicode(false);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Dob")
                        .HasColumnName("DOB")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("Ediid")
                        .HasColumnName("EDIID")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<int?>("GenderId")
                        .HasColumnName("GenderID")
                        .HasColumnType("int");

                    b.Property<string>("LocalId")
                        .HasColumnName("LocalID")
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256)
                        .IsUnicode(false);

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PostalCodeZip")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<int?>("TeacherId")
                        .HasColumnName("TeacherID")
                        .HasColumnType("int");

                    b.Property<int?>("YearId")
                        .HasColumnName("YearID")
                        .HasColumnType("int")
                        .HasComment("Year of the EDI implementation");

                    b.HasKey("Id");

                    b.HasIndex("GenderId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("YearId");

                    b.ToTable("Children","EDI");
                });

            modelBuilder.Entity("EDI.ApplicationCore.Entities.Coordinator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CoordinatorName")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(14)")
                        .HasMaxLength(14);

                    b.Property<string>("UserId")
                        .HasColumnName("UserID")
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<int?>("YearId")
                        .HasColumnName("YearID")
                        .HasColumnType("int")
                        .HasComment("Year of the EDI implementation");

                    b.HasKey("Id");

                    b.HasIndex("YearId");

                    b.ToTable("Coordinators","EDI");
                });

            modelBuilder.Entity("EDI.ApplicationCore.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Code")
                        .HasColumnName("Code")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("English")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("French")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("ISO2CountryCode")
                        .IsRequired()
                        .HasColumnName("ISO2CountryCode")
                        .HasColumnType("nvarchar(2)")
                        .HasMaxLength(2);

                    b.Property<string>("ISO3CountryCode")
                        .IsRequired()
                        .HasColumnName("ISO3CountryCode")
                        .HasColumnType("nvarchar(3)")
                        .HasMaxLength(3);

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Countries","LUData");
                });

            modelBuilder.Entity("EDI.ApplicationCore.Entities.DateDimension", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<byte>("DOWInMonth")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Day")
                        .HasColumnType("tinyint");

                    b.Property<short>("DayOfYear")
                        .HasColumnType("smallint");

                    b.Property<string>("DaySuffix")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .IsFixedLength(true)
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<DateTime>("FirstDayOfMonth")
                        .HasColumnType("date");

                    b.Property<DateTime>("FirstDayOfNextMonth")
                        .HasColumnType("date");

                    b.Property<DateTime>("FirstDayOfNextYear")
                        .HasColumnType("date");

                    b.Property<DateTime>("FirstDayOfQuarter")
                        .HasColumnType("date");

                    b.Property<DateTime>("FirstDayOfYear")
                        .HasColumnType("date");

                    b.Property<int>("FiscalYear")
                        .HasColumnType("int");

                    b.Property<int>("FiscalYearMonth")
                        .HasColumnType("int");

                    b.Property<int>("FiscalYearMonthOrder")
                        .HasColumnType("int");

                    b.Property<string>("HolidayText")
                        .HasColumnType("varchar(64)")
                        .HasMaxLength(64)
                        .IsUnicode(false);

                    b.Property<byte>("ISOWeekOfYear")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsHoliday")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWeekend")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastDayOfMonth")
                        .HasColumnType("date");

                    b.Property<DateTime>("LastDayOfQuarter")
                        .HasColumnType("date");

                    b.Property<DateTime>("LastDayOfYear")
                        .HasColumnType("date");

                    b.Property<byte>("Month")
                        .HasColumnType("tinyint");

                    b.Property<string>("MonthName")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<byte>("Quarter")
                        .HasColumnType("tinyint");

                    b.Property<string>("QuarterName")
                        .IsRequired()
                        .HasColumnType("varchar(6)")
                        .HasMaxLength(6)
                        .IsUnicode(false);

                    b.Property<string>("WeekDayName")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<byte>("WeekOfMonth")
                        .HasColumnType("tinyint");

                    b.Property<byte>("WeekOfYear")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Weekday")
                        .HasColumnType("tinyint");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.Property<int>("YearMonth")
                        .HasColumnType("int");

                    b.HasKey("Date");

                    b.ToTable("DateDimension");
                });

            modelBuilder.Entity("EDI.ApplicationCore.Entities.Faq", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Answer")
                        .HasColumnType("nvarchar(4000)")
                        .HasMaxLength(4000);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256)
                        .IsUnicode(false);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsAdministratorFaq")
                        .HasColumnName("IsAdministratorFAQ")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsCoordinatorFaq")
                        .HasColumnName("IsCoordinatorFAQ")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsTeacherFaq")
                        .HasColumnName("IsTeacherFAQ")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256)
                        .IsUnicode(false);

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Question")
                        .HasColumnType("nvarchar(4000)")
                        .HasMaxLength(4000);

                    b.Property<short>("Sequence")
                        .HasColumnType("smallint");

                    b.Property<int>("YearId")
                        .HasColumnName("YearID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("YearId");

                    b.ToTable("FAQ","EDI");
                });

            modelBuilder.Entity("EDI.ApplicationCore.Entities.FileImport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("ChildDob")
                        .HasColumnName("ChildDOB")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("ChildEdiid")
                        .HasColumnName("ChildEDIID")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("ChildPostalCodeZip")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("CoordinatorEmail")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("CoordinatorName")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256)
                        .IsUnicode(false);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FileImportStatusId")
                        .HasColumnName("FileImportStatusID")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<int?>("GenderId")
                        .HasColumnName("GenderID")
                        .HasColumnType("int");

                    b.Property<string>("LocalId")
                        .HasColumnName("LocalID")
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256)
                        .IsUnicode(false);

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SchoolName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeacherEmail")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("TeacherName")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("FileImportStatusId");

                    b.HasIndex("GenderId");

                    b.ToTable("FileImports","Staging");
                });

            modelBuilder.Entity("EDI.ApplicationCore.Entities.FileImportStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(3)")
                        .HasMaxLength(3);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256)
                        .IsUnicode(false);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("English")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("French")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256)
                        .IsUnicode(false);

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FileImportStatus","LUData");
                });

            modelBuilder.Entity("EDI.ApplicationCore.Entities.FormConfigurations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256)
                        .IsUnicode(false);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FieldName")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<string>("FormName")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256)
                        .IsUnicode(false);

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FormConfigurations");
                });

            modelBuilder.Entity("EDI.ApplicationCore.Entities.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(3)")
                        .HasMaxLength(3);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256)
                        .IsUnicode(false);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("English")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("French")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256)
                        .IsUnicode(false);

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Genders","LUData");
                });

            modelBuilder.Entity("EDI.ApplicationCore.Entities.InputType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256)
                        .IsUnicode(false);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("English")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("French")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256)
                        .IsUnicode(false);

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("YearId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("YearId");

                    b.ToTable("InputTypes","LUData");
                });

            modelBuilder.Entity("EDI.ApplicationCore.Entities.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(3)")
                        .HasMaxLength(3);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256)
                        .IsUnicode(false);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("English")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("French")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256)
                        .IsUnicode(false);

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Languages","LUData");
                });

            modelBuilder.Entity("EDI.ApplicationCore.Entities.Link", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256)
                        .IsUnicode(false);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(400)")
                        .HasMaxLength(400);

                    b.Property<bool?>("IsAdminLink")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsCoordinatorLink")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsTeacherLink")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256)
                        .IsUnicode(false);

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<short>("Sequence")
                        .HasColumnType("smallint");

                    b.Property<string>("Url")
                        .HasColumnName("URL")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<int>("YearId")
                        .HasColumnName("YearID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("YearId");

                    b.ToTable("Links","EDI");
                });

            modelBuilder.Entity("EDI.ApplicationCore.Entities.LookupSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256)
                        .IsUnicode(false);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LookupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256)
                        .IsUnicode(false);

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("YearId")
                        .HasColumnName("YearID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("YearId");

                    b.ToTable("LookupSets","LUData");
                });

            modelBuilder.Entity("EDI.ApplicationCore.Entities.LookupSetOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256)
                        .IsUnicode(false);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("English")
                        .IsRequired()
                        .HasColumnType("nvarchar(140)")
                        .HasMaxLength(140);

                    b.Property<string>("French")
                        .HasColumnType("nvarchar(140)")
                        .HasMaxLength(140);

                    b.Property<int>("LookupId")
                        .HasColumnName("LookupID")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256)
                        .IsUnicode(false);

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<short>("Sequence")
                        .HasColumnType("smallint");

                    b.Property<byte>("Value")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("LookupId");

                    b.ToTable("LookupSetOptions","LUData");
                });

            modelBuilder.Entity("EDI.ApplicationCore.Entities.MenuConfigurations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256)
                        .IsUnicode(false);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("English")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<bool>("ForAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("ForCoordinator")
                        .HasColumnType("bit");

                    b.Property<bool>("ForTeacher")
                        .HasColumnType("bit");

                    b.Property<string>("French")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<bool>("HasChild")
                        .HasColumnType("bit");

                    b.Property<string>("IconCss")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256)
                        .IsUnicode(false);

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NodeId")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<string>("PID")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<string>("URL")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("MenuConfigurations");
                });

            modelBuilder.Entity("EDI.ApplicationCore.Entities.NewsFeed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("Alberta")
                        .HasColumnType("bit");

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("BritishColumbia")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Manitoba")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("NewBrunswick")
                        .HasColumnType("bit");

                    b.Property<bool?>("Newfoundland")
                        .HasColumnType("bit");

                    b.Property<bool?>("NovaScotia")
                        .HasColumnType("bit");

                    b.Property<bool?>("Nunavut")
                        .HasColumnType("bit");

                    b.Property<bool?>("Nwt")
                        .HasColumnType("bit");

                    b.Property<bool?>("Ontario")
                        .HasColumnType("bit");

                    b.Property<bool?>("Pei")
                        .HasColumnType("bit");

                    b.Property<bool?>("Quebec")
                        .HasColumnType("bit");

                    b.Property<bool?>("Saskatchewan")
                        .HasColumnType("bit");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime2");

                    b.Property<int>("YearId")
                        .HasColumnType("int");

                    b.Property<bool?>("Yukon")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("YearId");

                    b.ToTable("NewsFeed","EDI");
                });

            modelBuilder.Entity("EDI.ApplicationCore.Entities.Orientation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256)
                        .IsUnicode(false);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("English")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("French")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256)
                        .IsUnicode(false);

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YearId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("YearId");

                    b.ToTable("Orientations","LUData");
                });

            modelBuilder.Entity("EDI.ApplicationCore.Entities.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("CountryID")
                        .HasColumnName("CountryID")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("EDICode")
                        .HasColumnType("tinyint");

                    b.Property<string>("English")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("French")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64);

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ProvinceTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryID");

                    b.HasIndex("ProvinceTypeId");

                    b.ToTable("Provinces","LUData");
                });

            modelBuilder.Entity("EDI.ApplicationCore.Entities.ProvinceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64);

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("ProvinceType","LUData");
                });

            modelBuilder.Entity("EDI.ApplicationCore.Entities.Questionnaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256)
                        .IsUnicode(false);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionEnglish")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("DescriptionFrench")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("English")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("French")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256)
                        .IsUnicode(false);

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("QuestionnaireName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<bool?>("ShowProgressBar")
                        .HasColumnType("bit")
                        .HasComment("Answered x of y Questions");

                    b.Property<bool?>("ShowQuestionNumbers")
                        .HasColumnType("bit");

                    b.Property<int>("YearId")
                        .HasColumnName("YearID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("YearId");

                    b.ToTable("Questionnaires","EDI");
                });

            modelBuilder.Entity("EDI.ApplicationCore.Entities.QuestionnairesConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("Alberta")
                        .HasColumnType("bit");

                    b.Property<bool?>("BritishColumbia")
                        .HasColumnType("bit");

                    b.Property<byte?>("ColumnSpan")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Columns")
                        .HasColumnType("tinyint");

                    b.Property<string>("Condition")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256)
                        .IsUnicode(false);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("English")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("EntityField")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("French")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("GroupName")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<bool>("HasHelp")
                        .HasColumnType("bit");

                    b.Property<bool>("HasLookupEntity")
                        .HasColumnType("bit");

                    b.Property<bool>("HasNotification")
                        .HasColumnType("bit");

                    b.Property<string>("HelpText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InputTypeId")
                        .HasColumnName("InputTypeID")
                        .HasColumnType("int");

                    b.Property<bool>("IsConditional")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsNewGroup")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsReadOnly")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("LookupEntity")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int?>("LookupEntityId")
                        .HasColumnName("LookupEntityID")
                        .HasColumnType("int");

                    b.Property<bool?>("Manitoba")
                        .HasColumnType("bit");

                    b.Property<string>("Mask")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<byte?>("MaxLength")
                        .HasColumnType("tinyint");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256)
                        .IsUnicode(false);

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("NewBrunswick")
                        .HasColumnType("bit");

                    b.Property<bool?>("Newfoundland")
                        .HasColumnType("bit");

                    b.Property<string>("Notification")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("NotificationCondition")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<bool?>("NovaScotia")
                        .HasColumnType("bit");

                    b.Property<bool?>("Nunavut")
                        .HasColumnType("bit");

                    b.Property<bool?>("Nwt")
                        .HasColumnName("NWT")
                        .HasColumnType("bit");

                    b.Property<bool?>("Ontario")
                        .HasColumnType("bit");

                    b.Property<int?>("OrientationId")
                        .HasColumnName("OrientationID")
                        .HasColumnType("int");

                    b.Property<bool?>("Pei")
                        .HasColumnName("PEI")
                        .HasColumnType("bit");

                    b.Property<bool?>("Quebec")
                        .HasColumnType("bit");

                    b.Property<string>("QuestionNumber")
                        .HasColumnType("nvarchar(5)")
                        .HasMaxLength(5);

                    b.Property<int>("QuestionnaireId")
                        .HasColumnName("QuestionnaireID")
                        .HasColumnType("int");

                    b.Property<bool>("RepeatHeader")
                        .HasColumnType("bit");

                    b.Property<bool?>("Saskatchewan")
                        .HasColumnType("bit");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("VariableName")
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Variable Name for data dictionary")
                        .HasMaxLength(50);

                    b.Property<int?>("YearId")
                        .HasColumnType("int");

                    b.Property<bool?>("Yukon")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("InputTypeId");

                    b.HasIndex("OrientationId");

                    b.HasIndex("QuestionnaireId");

                    b.HasIndex("YearId");

                    b.ToTable("Questionnaires.Configuration","EDI");
                });

            modelBuilder.Entity("EDI.ApplicationCore.Entities.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256)
                        .IsUnicode(false);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256)
                        .IsUnicode(false);

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<string>("SchoolName")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<string>("SchoolNumber")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<int>("SiteId")
                        .HasColumnType("int");

                    b.Property<int?>("YearId")
                        .HasColumnName("YearID")
                        .HasColumnType("int")
                        .HasComment("Year of the EDI implementation");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("ProvinceId");

                    b.HasIndex("SiteId");

                    b.HasIndex("YearId");

                    b.ToTable("Schools","EDI");
                });

            modelBuilder.Entity("EDI.ApplicationCore.Entities.Site", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CoordinatorId")
                        .HasColumnType("int")
                        .IsUnicode(false);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256)
                        .IsUnicode(false);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256)
                        .IsUnicode(false);

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SiteName")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<string>("SiteNumber")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<int?>("YearId")
                        .HasColumnName("YearID")
                        .HasColumnType("int")
                        .HasComment("Year of the EDI implementation");

                    b.HasKey("Id");

                    b.HasIndex("CoordinatorId");

                    b.HasIndex("YearId");

                    b.ToTable("Sites","EDI");
                });

            modelBuilder.Entity("EDI.ApplicationCore.Entities.SpecialProblem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(3)")
                        .HasMaxLength(3);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256)
                        .IsUnicode(false);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("English")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("French")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256)
                        .IsUnicode(false);

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SpecialProblems","LUData");
                });

            modelBuilder.Entity("EDI.ApplicationCore.Entities.SystemConfigurations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256)
                        .IsUnicode(false);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FieldName")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<string>("FieldValue")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256)
                        .IsUnicode(false);

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SystemConfigurations","dbo");
                });

            modelBuilder.Entity("EDI.ApplicationCore.Entities.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256)
                        .IsUnicode(false);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256)
                        .IsUnicode(false);

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(14)")
                        .HasMaxLength(14);

                    b.Property<int?>("SchoolId")
                        .HasColumnName("SchoolID")
                        .HasColumnType("int");

                    b.Property<string>("TeacherName")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("TeacherNumber")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("UserId")
                        .HasColumnName("UserID")
                        .HasColumnType("nvarchar(40)")
                        .HasComment("Links to user in EDI.Identity database")
                        .HasMaxLength(40);

                    b.Property<int?>("YearId")
                        .HasColumnName("YearID")
                        .HasColumnType("int")
                        .HasComment("Year of the EDI implementation");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.HasIndex("YearId");

                    b.ToTable("Teachers","EDI");
                });

            modelBuilder.Entity("EDI.ApplicationCore.Entities.TeacherFeedbackForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CommentsFeedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("CompletedPaperVersion")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("ContentClearlyPresented")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("ContentQualityPresentations")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("ContentRelevant")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("ContentUsefulnessOfHandouts")
                        .HasColumnType("tinyint");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256)
                        .IsUnicode(false);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("FirstTimeCompletingEdi")
                        .HasColumnName("FirstTimeCompletingEDI")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("FirstTraining")
                        .HasColumnType("tinyint");

                    b.Property<string>("LanguageCompleted")
                        .HasColumnType("nvarchar(20)")
                        .HasComment("English or French")
                        .HasMaxLength(20);

                    b.Property<byte?>("MaterialsGuestSpeaker")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("MaterialsHistory")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("MaterialsOther")
                        .HasColumnType("tinyint");

                    b.Property<string>("MaterialsOtherSpecify")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<byte?>("MaterialsPastEdi")
                        .HasColumnName("MaterialsPastEDI")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("MaterialsPpt")
                        .HasColumnName("MaterialsPPT")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("MaterialsTimeToStart")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("MaterialsTrainingInComputerLab")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("MaterialsVideo")
                        .HasColumnType("tinyint");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256)
                        .IsUnicode(false);

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MostBeneficial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("OverallAssessment")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("ProcessDiscussion")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("ProcessInteration")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("ProcessOrganization")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("ProcessQuestions")
                        .HasColumnType("tinyint");

                    b.Property<int>("TeacherId")
                        .HasColumnName("TeacherID")
                        .HasColumnType("int");

                    b.Property<byte?>("VersionPreferred")
                        .HasColumnType("tinyint");

                    b.Property<int?>("YearId")
                        .HasColumnName("YearID")
                        .HasColumnType("int")
                        .HasComment("Year of the EDI implementation");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.HasIndex("YearId");

                    b.ToTable("TeacherFeedbackForms","EDI_Forms");
                });

            modelBuilder.Entity("EDI.ApplicationCore.Entities.TeacherParticipationForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte?>("Age")
                        .HasColumnType("tinyint");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256)
                        .IsUnicode(false);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("EducationBachelorDegree")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("EducationBachelorEducationDegree")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("EducationMastersCourses")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("EducationMastersDegree")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("EducationOther")
                        .HasColumnType("tinyint");

                    b.Property<string>("EducationOtherComment")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<byte?>("EducationPhd")
                        .HasColumnName("EducationPHD")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("EducationPhdcourses")
                        .HasColumnName("EducationPHDCourses")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("EducationPostBachelorCertificate")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("EducationPostBachelorCourses")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("EducationSomeCoursesBachelors")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("EducationTeachingCertificate")
                        .HasColumnType("tinyint");

                    b.Property<short?>("ExperienceAtClassInMonths")
                        .HasColumnType("smallint");

                    b.Property<short?>("ExperienceGradeInMonths")
                        .HasColumnType("smallint");

                    b.Property<short?>("ExperienceInMonths")
                        .HasColumnType("smallint");

                    b.Property<short?>("ExperienceSchoolInMonths")
                        .HasColumnType("smallint");

                    b.Property<byte?>("FirstTimeCompletingEdi")
                        .HasColumnName("FirstTimeCompletingEDI")
                        .HasColumnType("tinyint");

                    b.Property<int?>("GenderId")
                        .HasColumnName("GenderID")
                        .HasColumnType("int");

                    b.Property<byte?>("GuideNotUsedDidntHave")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("GuideNotUsedFamiliar")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("GuideNotUsedNoTime")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("GuideNotUsedNotHelpful")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("GuideOther")
                        .HasColumnType("tinyint");

                    b.Property<string>("GuideOtherComment")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<byte?>("GuideUsedHelpful")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("GuideUsedNotHelpful")
                        .HasColumnType("tinyint");

                    b.Property<string>("LanguageCompleted")
                        .HasColumnType("nvarchar(20)")
                        .HasComment("English or French")
                        .HasMaxLength(20);

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256)
                        .IsUnicode(false);

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("PreviouslyAttendedTeacherTraining")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("StudentCount")
                        .HasColumnType("tinyint");

                    b.Property<int>("TeacherId")
                        .HasColumnName("TeacherID")
                        .HasColumnType("int");

                    b.Property<byte?>("TeacherTrainingForThisImplementation")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("TeacherTrainingUsefulness")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("TimesAttendedTeacherTraining")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("TimesCompletedEdi")
                        .HasColumnName("TimesCompletedEDI")
                        .HasColumnType("tinyint")
                        .HasComment("1-4 or more");

                    b.Property<int?>("YearId")
                        .HasColumnName("YearID")
                        .HasColumnType("int")
                        .HasComment("Year of the EDI implementation");

                    b.HasKey("Id");

                    b.HasIndex("GenderId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("YearId");

                    b.ToTable("TeacherParticipationForms","EDI_Forms");
                });

            modelBuilder.Entity("EDI.ApplicationCore.Entities.Translation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256)
                        .IsUnicode(false);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("English")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("French")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256)
                        .IsUnicode(false);

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Translations","LUData");
                });

            modelBuilder.Entity("EDI.ApplicationCore.Entities.Year", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("Alberta")
                        .HasColumnType("bit");

                    b.Property<bool?>("BritishColumbia")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256)
                        .IsUnicode(false);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<short?>("Ediyear")
                        .HasColumnName("EDIYear")
                        .HasColumnType("smallint");

                    b.Property<bool?>("Manitoba")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256)
                        .IsUnicode(false);

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("NewBrunswick")
                        .HasColumnType("bit");

                    b.Property<bool?>("Newfoundland")
                        .HasColumnType("bit");

                    b.Property<bool?>("NovaScotia")
                        .HasColumnType("bit");

                    b.Property<bool?>("Nunavut")
                        .HasColumnType("bit");

                    b.Property<bool?>("Nwt")
                        .HasColumnType("bit");

                    b.Property<bool?>("Ontario")
                        .HasColumnType("bit");

                    b.Property<bool?>("Pei")
                        .HasColumnType("bit");

                    b.Property<bool?>("Quebec")
                        .HasColumnType("bit");

                    b.Property<bool?>("Saskatchewan")
                        .HasColumnType("bit");

                    b.Property<bool?>("Yukon")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Years","LUData");
                });

            modelBuilder.Entity("EDI.ApplicationCore.Entities.Child", b =>
                {
                    b.HasOne("EDI.ApplicationCore.Entities.Gender", "Gender")
                        .WithMany("Children")
                        .HasForeignKey("GenderId")
                        .HasConstraintName("FK_Children_Gender");

                    b.HasOne("EDI.ApplicationCore.Entities.Teacher", "Teacher")
                        .WithMany("Children")
                        .HasForeignKey("TeacherId")
                        .HasConstraintName("FK_Children_Teachers")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EDI.ApplicationCore.Entities.Year", "Year")
                        .WithMany("Children")
                        .HasForeignKey("YearId")
                        .HasConstraintName("FK_Years_Children");
                });

            modelBuilder.Entity("EDI.ApplicationCore.Entities.Coordinator", b =>
                {
                    b.HasOne("EDI.ApplicationCore.Entities.Year", "Year")
                        .WithMany("Coordinators")
                        .HasForeignKey("YearId")
                        .HasConstraintName("FK_Years_Coordinators");
                });

            modelBuilder.Entity("EDI.ApplicationCore.Entities.Faq", b =>
                {
                    b.HasOne("EDI.ApplicationCore.Entities.Year", "Year")
                        .WithMany("Faqs")
                        .HasForeignKey("YearId")
                        .HasConstraintName("FK_Years_FAQ")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EDI.ApplicationCore.Entities.FileImport", b =>
                {
                    b.HasOne("EDI.ApplicationCore.Entities.FileImportStatus", "FileImportStatus")
                        .WithMany("FileImports")
                        .HasForeignKey("FileImportStatusId")
                        .HasConstraintName("FK_FileImports_FileImportStatus");

                    b.HasOne("EDI.ApplicationCore.Entities.Gender", "Gender")
                        .WithMany("FileImports")
                        .HasForeignKey("GenderId")
                        .HasConstraintName("FK_FileImports_Gender");
                });

            modelBuilder.Entity("EDI.ApplicationCore.Entities.InputType", b =>
                {
                    b.HasOne("EDI.ApplicationCore.Entities.Year", "Year")
                        .WithMany("InputTypes")
                        .HasForeignKey("YearId")
                        .HasConstraintName("FK_Years_InputTypes")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EDI.ApplicationCore.Entities.Link", b =>
                {
                    b.HasOne("EDI.ApplicationCore.Entities.Year", "Year")
                        .WithMany("Links")
                        .HasForeignKey("YearId")
                        .HasConstraintName("FK_Years_Links")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EDI.ApplicationCore.Entities.LookupSet", b =>
                {
                    b.HasOne("EDI.ApplicationCore.Entities.Year", "Year")
                        .WithMany("LookupSets")
                        .HasForeignKey("YearId")
                        .HasConstraintName("FK_Years_LookupSets")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EDI.ApplicationCore.Entities.LookupSetOption", b =>
                {
                    b.HasOne("EDI.ApplicationCore.Entities.LookupSet", "LookupSet")
                        .WithMany("LookupSetOptions")
                        .HasForeignKey("LookupId")
                        .HasConstraintName("FK_LookupSetOptions_LookupSets")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EDI.ApplicationCore.Entities.NewsFeed", b =>
                {
                    b.HasOne("EDI.ApplicationCore.Entities.Year", "Year")
                        .WithMany("NewsFeeds")
                        .HasForeignKey("YearId")
                        .HasConstraintName("FK_Years_NewsFeeds")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EDI.ApplicationCore.Entities.Orientation", b =>
                {
                    b.HasOne("EDI.ApplicationCore.Entities.Year", "Year")
                        .WithMany("Orientations")
                        .HasForeignKey("YearId")
                        .HasConstraintName("FK_Years_Orientations")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EDI.ApplicationCore.Entities.Province", b =>
                {
                    b.HasOne("EDI.ApplicationCore.Entities.Country", "Country")
                        .WithMany("Provinces")
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EDI.ApplicationCore.Entities.ProvinceType", "ProvinceType")
                        .WithMany("Provinces")
                        .HasForeignKey("ProvinceTypeId");
                });

            modelBuilder.Entity("EDI.ApplicationCore.Entities.Questionnaire", b =>
                {
                    b.HasOne("EDI.ApplicationCore.Entities.Year", "Year")
                        .WithMany("Questionnaires")
                        .HasForeignKey("YearId")
                        .HasConstraintName("FK_Years_Questionnaires")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EDI.ApplicationCore.Entities.QuestionnairesConfiguration", b =>
                {
                    b.HasOne("EDI.ApplicationCore.Entities.InputType", "InputType")
                        .WithMany("QuestionnairesConfigurations")
                        .HasForeignKey("InputTypeId")
                        .HasConstraintName("FK_Questionnaires.Configuration_InputTypes")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EDI.ApplicationCore.Entities.Orientation", "Orientation")
                        .WithMany("QuestionnairesConfigurations")
                        .HasForeignKey("OrientationId")
                        .HasConstraintName("FK_Questionnaires.Configuration_Orientation")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("EDI.ApplicationCore.Entities.Questionnaire", "Questionnaire")
                        .WithMany("QuestionnairesConfigurations")
                        .HasForeignKey("QuestionnaireId")
                        .HasConstraintName("FK_Questionnaires.Configuration_Questionnaires")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EDI.ApplicationCore.Entities.Year", null)
                        .WithMany("QuestionnairesConfigurations")
                        .HasForeignKey("YearId");
                });

            modelBuilder.Entity("EDI.ApplicationCore.Entities.School", b =>
                {
                    b.HasOne("EDI.ApplicationCore.Entities.Country", "Country")
                        .WithMany("Schools")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EDI.ApplicationCore.Entities.Province", "Province")
                        .WithMany("Schools")
                        .HasForeignKey("ProvinceId")
                        .HasConstraintName("FK_Schools_Provinces")
                        .IsRequired();

                    b.HasOne("EDI.ApplicationCore.Entities.Site", "Site")
                        .WithMany("Schools")
                        .HasForeignKey("SiteId")
                        .HasConstraintName("FK_Schools_Sites")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EDI.ApplicationCore.Entities.Year", "Year")
                        .WithMany("Schools")
                        .HasForeignKey("YearId")
                        .HasConstraintName("FK_Years_Schools");
                });

            modelBuilder.Entity("EDI.ApplicationCore.Entities.Site", b =>
                {
                    b.HasOne("EDI.ApplicationCore.Entities.Coordinator", "Coordinator")
                        .WithMany("Sites")
                        .HasForeignKey("CoordinatorId")
                        .HasConstraintName("FK_Coordinators_Sites")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EDI.ApplicationCore.Entities.Year", "Year")
                        .WithMany("Sites")
                        .HasForeignKey("YearId")
                        .HasConstraintName("FK_Years_Sites")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EDI.ApplicationCore.Entities.Teacher", b =>
                {
                    b.HasOne("EDI.ApplicationCore.Entities.School", "School")
                        .WithMany("Teachers")
                        .HasForeignKey("SchoolId")
                        .HasConstraintName("FK_Teachers_Schools")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EDI.ApplicationCore.Entities.Year", "Year")
                        .WithMany("Teachers")
                        .HasForeignKey("YearId")
                        .HasConstraintName("FK_Years_Teachers");
                });

            modelBuilder.Entity("EDI.ApplicationCore.Entities.TeacherFeedbackForm", b =>
                {
                    b.HasOne("EDI.ApplicationCore.Entities.Teacher", "Teacher")
                        .WithMany("TeacherFeedbackForms")
                        .HasForeignKey("TeacherId")
                        .HasConstraintName("FK_TeacherFeedback_Teachers")
                        .IsRequired();

                    b.HasOne("EDI.ApplicationCore.Entities.Year", "Year")
                        .WithMany("TeacherFeedbackForms")
                        .HasForeignKey("YearId")
                        .HasConstraintName("FK_Years_TeacherFeedbackForms");
                });

            modelBuilder.Entity("EDI.ApplicationCore.Entities.TeacherParticipationForm", b =>
                {
                    b.HasOne("EDI.ApplicationCore.Entities.Gender", "Gender")
                        .WithMany("TeacherParticipationForms")
                        .HasForeignKey("GenderId")
                        .HasConstraintName("FK_TeacherParticipationForms_Gender");

                    b.HasOne("EDI.ApplicationCore.Entities.Teacher", "Teacher")
                        .WithMany("TeacherParticipationForms")
                        .HasForeignKey("TeacherId")
                        .HasConstraintName("FK_TeacherParticipation_Teachers")
                        .IsRequired();

                    b.HasOne("EDI.ApplicationCore.Entities.Year", "Year")
                        .WithMany("TeacherParticipationForms")
                        .HasForeignKey("YearId")
                        .HasConstraintName("FK_Years_TeacherParticipationForms");
                });
#pragma warning restore 612, 618
        }
    }
}
